In [1]:
import numpy as np
import pandas as pd

In [3]:
data=pd.read_csv(r"C:\5_6136515016142095058.csv")

In [4]:
data.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [5]:
data.isnull().sum()

Species    0
Weight     0
Length1    0
Length2    0
Length3    0
Height     0
Width      0
dtype: int64

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
Species    159 non-null object
Weight     159 non-null float64
Length1    159 non-null float64
Length2    159 non-null float64
Length3    159 non-null float64
Height     159 non-null float64
Width      159 non-null float64
dtypes: float64(6), object(1)
memory usage: 8.8+ KB


In [7]:
data.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [8]:
data.shape

(159, 7)

In [9]:
data.Species.unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [10]:
x=data.iloc[:,[0,2,3,4,5,6]].values
y=data.iloc[:,1].values

In [11]:
x

array([['Bream', 23.2, 25.4, 30.0, 11.52, 4.02],
       ['Bream', 24.0, 26.3, 31.2, 12.48, 4.3056],
       ['Bream', 23.9, 26.5, 31.1, 12.3778, 4.6961],
       ['Bream', 26.3, 29.0, 33.5, 12.73, 4.4555],
       ['Bream', 26.5, 29.0, 34.0, 12.444, 5.1339999999999995],
       ['Bream', 26.8, 29.7, 34.7, 13.6024, 4.9274],
       ['Bream', 26.8, 29.7, 34.5, 14.1795, 5.2785],
       ['Bream', 27.6, 30.0, 35.0, 12.67, 4.69],
       ['Bream', 27.6, 30.0, 35.1, 14.0049, 4.8438],
       ['Bream', 28.5, 30.7, 36.2, 14.2266, 4.9594],
       ['Bream', 28.4, 31.0, 36.2, 14.2628, 5.1042],
       ['Bream', 28.7, 31.0, 36.2, 14.3714, 4.8146],
       ['Bream', 29.1, 31.5, 36.4, 13.7592, 4.368],
       ['Bream', 29.5, 32.0, 37.3, 13.9129, 5.0728],
       ['Bream', 29.4, 32.0, 37.2, 14.9544, 5.1708],
       ['Bream', 29.4, 32.0, 37.2, 15.437999999999999, 5.58],
       ['Bream', 30.4, 33.0, 38.3, 14.8604, 5.2854],
       ['Bream', 30.4, 33.0, 38.5, 14.937999999999999, 5.1975],
       ['Bream', 30.9, 33.5,

In [12]:
y

array([ 242. ,  290. ,  340. ,  363. ,  430. ,  450. ,  500. ,  390. ,
        450. ,  500. ,  475. ,  500. ,  500. ,  340. ,  600. ,  600. ,
        700. ,  700. ,  610. ,  650. ,  575. ,  685. ,  620. ,  680. ,
        700. ,  725. ,  720. ,  714. ,  850. , 1000. ,  920. ,  955. ,
        925. ,  975. ,  950. ,   40. ,   69. ,   78. ,   87. ,  120. ,
          0. ,  110. ,  120. ,  150. ,  145. ,  160. ,  140. ,  160. ,
        169. ,  161. ,  200. ,  180. ,  290. ,  272. ,  390. ,  270. ,
        270. ,  306. ,  540. ,  800. , 1000. ,   55. ,   60. ,   90. ,
        120. ,  150. ,  140. ,  170. ,  145. ,  200. ,  273. ,  300. ,
          5.9,   32. ,   40. ,   51.5,   70. ,  100. ,   78. ,   80. ,
         85. ,   85. ,  110. ,  115. ,  125. ,  130. ,  120. ,  120. ,
        130. ,  135. ,  110. ,  130. ,  150. ,  145. ,  150. ,  170. ,
        225. ,  145. ,  188. ,  180. ,  197. ,  218. ,  300. ,  260. ,
        265. ,  250. ,  250. ,  300. ,  320. ,  514. ,  556. ,  840. ,
      

In [13]:
x.shape

(159, 6)

In [14]:
y.shape

(159,)

In [15]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([("oh",OneHotEncoder(),[0])],remainder="passthrough")
x=ct.fit_transform(x)

In [16]:
x

array([[1.0, 0.0, 0.0, ..., 30.0, 11.52, 4.02],
       [1.0, 0.0, 0.0, ..., 31.2, 12.48, 4.3056],
       [1.0, 0.0, 0.0, ..., 31.1, 12.3778, 4.6961],
       ...,
       [0.0, 0.0, 0.0, ..., 13.8, 2.2769999999999997, 1.2558],
       [0.0, 0.0, 0.0, ..., 15.2, 2.8728, 2.0672],
       [0.0, 0.0, 0.0, ..., 16.2, 2.9322, 1.8792]], dtype=object)

In [17]:
x.shape

(159, 12)

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [19]:
from sklearn.linear_model import LinearRegression
mlr=LinearRegression()
mlr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [20]:
ypred=mlr.predict(x_test)

In [21]:
ypred

array([ 428.88533577,   98.08363614,  216.67998922,  208.66936638,
        657.24094116,  876.38855413,  665.97861965,  407.27203048,
        965.65306863,  146.62291102,  255.15532231,  561.63685124,
        765.67575361, 1012.38234027, -118.72798063,   14.47341216,
        137.60789564, 1155.53572308,  170.97092949,  724.93548455,
       -128.48675188,  525.45508599,  175.3519065 , 1322.74816983,
        -23.0873263 ,  475.44172778,  719.96841977,  280.94571114,
        885.12085107,  -16.63412226,  585.26038657,  164.22863371])

In [22]:
y_test

array([ 390. ,    0. ,  170. ,  160. ,  556. ,  900. ,  800. ,  300. ,
        975. ,  115. ,  200. ,  456. , 1000. , 1000. ,   60. ,   78. ,
        145. , 1600. ,  130. ,  720. ,   55. ,  390. ,  120. , 1650. ,
         90. ,  450. ,  700. ,  270. ,  850. ,    9.7,  650. ,  110. ])

In [23]:
x_test

array([[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 27.6, 30.0, 35.0, 12.67, 4.69],
       [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 19.0, 20.5, 22.8, 6.4752,
        3.3516],
       [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 21.5, 23.5, 25.0, 6.275,
        3.725],
       [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 20.5, 22.5, 25.3, 7.0334,
        3.8203],
       [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 32.0, 34.5, 36.5, 10.2565,
        6.3875],
       [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 37.0, 40.0, 42.5, 11.73,
        7.225],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 33.7, 36.4, 39.6, 11.7612,
        6.5736],
       [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 34.8, 37.3, 39.8, 6.2884,
        4.0198],
       [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 37.4, 41.0, 45.9, 18.6354,
        6.7473],
       [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 19.0, 21.0, 22.5, 5.9175,
        3.3075],
       [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 30.0, 32.3, 34.8, 5.568,
        3.3756],
       [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 40.0, 42.5, 45.5, 7.28,


In [24]:
from sklearn.metrics import r2_score
accuracy=r2_score(ypred,y_test)

In [25]:
accuracy

0.8813066271385555

In [26]:
data.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [27]:
yp=mlr.predict(ct.transform([["Bream",24.0,26.3,31.2,12.4800,4.3056]]))

In [28]:
yp

array([330.3775134])